### ISSUE TITLE
Mouse pointer changed to "grab" instead of "clickable"

### ISSUE THREAD

**Issue by nebadom** [mapbox/leaflet-terminator#5]
I found this plugin very usefull, but I noticed that when you move mouse over the "night" area, it changed the pointer to "clickable".

Since my application has a huge amount of customization, (cluster, spiderfy, context menu, awesome-icons, and now terminator), it is kind of confusing that the pointer changed over "night". So, I wanted the terminator area to keep the pointer in "grab" mode.

It was kind of easy to do, but perhaps you could notify how to do it for future users:

1)  On the line 26, I added this code:
```javascript
className: 'leaflet-terminator'
```
So the chunk of code looks like this:
```javascript
L.Terminator = L.Polygon.extend({
    options: {
	color: '#00',
	opacity: 0.5,
	fillColor: '#00',
	fillOpacity: 0.5,
	resolution: 2,
	className: 'leaflet-terminator'
    },
```
This adds a class named "leaflet-terminator" to the terminator polygon area.

And on my css file, I added this class:
```css
.leaflet-terminator {
	cursor: -webkit-grab;
	cursor: -moz-grab;
}
```
So, now it displays the pointer as usual. Perhaps some other users found this usefull.

**Comment by boomsya** [comment]
thanks. helps me too

**Comment by omeek** [comment]
Just what I was looking for, thanks!
